plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'

}

android {
    namespace 'com.racks.parentalcontrol.child'
    compileSdk = 37

    defaultConfig {
        applicationId "com.racks.parentalcontrol.child"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "ParentSync-ChildApp-${variant.versionName}-${variant.buildType.name}.apk"
        }
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation(platform(libs.firebase.bom))

    implementation libs.gson
    implementation libs.webrtc
    implementation libs.permissionx
    implementation libs.firebase.database
    implementation libs.firebase.auth
    implementation libs.firebase.storage
    implementation libs.firebase.messaging

    implementation libs.play.services.location

    implementation libs.ssp.android
    implementation libs.sdp.android
}
